version: "3.2"
services:
  web:
    image: felep/dv1562
    volumes:
      - type: bind
        source: /home/filip/mylogs
        target: /var/log/mylogs
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
networks:
  volumes:
  webnet: